name: "Run type checker"
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pipenv
        run: |
          npm ci
      - name: Type check with mypy
        run: |
          npx prettier ./src
